name: Build & Publish Debug APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
  - name: Sign Android release
    steps:
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
