# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  main:
    runs-on: ubuntu-latest
  steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Send mail
        uses: ./
        with:
          server_address: ${{secrets.ADDRESS}}
          server_port: 465
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          subject: ${{github.repository}}
          body: ${{matrix.body}}
          to: ${{github.event.pusher.email}}
          from: github-actions
          content_type: ${{matrix.content_type}}
          attachments: ${{matrix.attachments}}
